### ISSUE TITLE
FOSS4G todo list

### ISSUE THREAD

**Issue by fredj** [pgRouting/workshop#17]
debian package build

debian package install inside the virtualbox, http://trac.osgeo.org/osgeo/wiki/Live_GIS_Workshop_Install

osm import area (chapter 3.4), see https://github.com/pgRouting/workshop-build/issues/2

ol3 chapter:
- [ ] initial extent (from chapter 3.4, Nottingham ?)
- [ ] server address (`localhost:xxxx`) 
- [ ] server GET params

server (geoserver?) chapter
